CREATE DATABASE AuthService;

CREATE TABLE [User] (
    UserId INT IDENTITY PRIMARY KEY,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    DeletedAt DATETIME DEFAULT NULL
);

CREATE TABLE RefreshToken (
    RefreshTokenId INT IDENTITY PRIMARY KEY,
    RefreshToken VARCHAR(255) NOT NULL,
    UserId INT REFERENCES [User](UserId),
    CreatedAt DATETIME DEFAULT GETDATE(),
    ExpiresAt DATETIME,
    RevokedAt DATETIME DEFAULT NULL,
    LastUsedAt DATETIME DEFAULT NULL
);
