CREATE DATABASE AuthService;

CREATE TABLE [User] (
    UserId INT IDENTITY PRIMARY KEY,
    Username VARCHAR(20) UNIQUE NOT NULL,
    Email VARCHAR(254) UNIQUE NOT NULL,
    PasswordHash VARCHAR(256) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    DeletedAt DATETIME DEFAULT NULL
);

CREATE TABLE RefreshToken (
    RefreshTokenId INT IDENTITY PRIMARY KEY,
    Token VARCHAR(2048) NOT NULL,
    UserId INT UNIQUE REFERENCES [User](UserId),
    IssuedAt DATETIME NOT NULL DEFAULT GETDATE(),
    ExpiresAt DATETIME NOT NULL
);